//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLSTemplate
    {
        public int BLSID { get; set; }
        public int ActID { get; set; }
        public bool IsDescription { get; set; }
        public string BLSQL { get; set; }
        public string SFSQL { get; set; }
        public string SBSQL { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsScheduleActivity { get; set; }
        public Nullable<int> WFID { get; set; }
    }
}
