//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOL()
        {
            this.BOLDetails = new HashSet<BOLDetails>();
        }
    
        public int BOLID { get; set; }
        public int BOLReasonID { get; set; }
        public string LoadNo { get; set; }
        public int ProjectSCID { get; set; }
        public System.DateTime BOLDate { get; set; }
        public System.DateTime ShippedDate { get; set; }
        public string TruckingCompany { get; set; }
        public string Carrier { get; set; }
        public string Consignee { get; set; }
        public string Destination { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual BOLReason BOLReason { get; set; }
        public virtual ProjectScoreCard ProjectScoreCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLDetails> BOLDetails { get; set; }
    }
}
