//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLDetails
    {
        public int BOLDetailID { get; set; }
        public int BOLID { get; set; }
        public int ScopeID { get; set; }
        public string ControlNumber { get; set; }
        public string ISONumber { get; set; }
        public string IWPNumber { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual BOL BOL { get; set; }
        public virtual Scope Scope { get; set; }
    }
}
