//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCodeLog
    {
        public int CostCodeLogID { get; set; }
        public int CostCodeID { get; set; }
        public string OldValueCCNumber { get; set; }
        public string NewValueCCNumber { get; set; }
        public string OldValueCCDescription { get; set; }
        public string NewValueCCDescription { get; set; }
        public string OldValueCostType { get; set; }
        public string NewValueCostType { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CostCode CostCode { get; set; }
    }
}
