//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDAcornPipeSize
    {
        public string ControlNo { get; set; }
        public string PipeSize { get; set; }
        public string Revision { get; set; }
        public string Descr { get; set; }
    }
}
