//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDRevByISO
    {
        public string ProjectID { get; set; }
        public string Isometric { get; set; }
        public string CostCode { get; set; }
        public decimal Hrs { get; set; }
        public decimal Qty { get; set; }
    }
}
