//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDSmartPlantMA
    {
        public string ISO { get; set; }
        public string Ctl { get; set; }
        public int ItemsCount { get; set; }
        public int ItemsShort { get; set; }
    }
}
