//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAssignment
    {
        public int DocumentAssignmentID { get; set; }
        public int DocumentID { get; set; }
        public Nullable<int> QCSystemID { get; set; }
        public Nullable<int> QCAreaID { get; set; }
        public Nullable<int> QCTagID { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CompletedBy { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual QCArea QCArea { get; set; }
        public virtual QCSystem QCSystem { get; set; }
        public virtual QCTag QCTag { get; set; }
    }
}
