//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DurationType_Default
    {
        public int MatGroupId { get; set; }
        public int DILow { get; set; }
        public int DIUP { get; set; }
        public string Destination { get; set; }
    }
}
