//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duration_CompactDefaults
    {
        public int RowId { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<bool> IsDescription { get; set; }
        public string ActivityName { get; set; }
        public int Duration { get; set; }
        public string MaterialType { get; set; }
        public string DIClass { get; set; }
        public string Destination { get; set; }
        public Nullable<bool> IsScheduleActivity { get; set; }
        public Nullable<int> WFID { get; set; }
    }
}
