//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDataDescriptionDetail
    {
        public int ImportDataDescriptionDetailID { get; set; }
        public int ImportDataID { get; set; }
        public int ProjectSCDescriptionID { get; set; }
    
        public virtual ImportData ImportData { get; set; }
        public virtual ProjectSCDescription ProjectSCDescription { get; set; }
    }
}
