//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressLog
    {
        public int ProgressLogID { get; set; }
        public int ScopeID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> ImportLogID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> OldProgress { get; set; }
        public Nullable<decimal> NewProgress { get; set; }
        public string OldScheduleID { get; set; }
        public string NewScheduleID { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> OldDateProgress { get; set; }
        public Nullable<System.DateTime> NewDateProgress { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ImportLog ImportLog { get; set; }
        public virtual Scope Scope { get; set; }
    }
}
