//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectScoreCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectScoreCard()
        {
            this.BOL = new HashSet<BOL>();
            this.DurationType = new HashSet<DurationType>();
            this.G = new HashSet<G>();
            this.ImportLog = new HashSet<ImportLog>();
            this.ProjectSCActivity = new HashSet<ProjectSCActivity>();
            this.ProjectSCBLS = new HashSet<ProjectSCBLS>();
            this.ProjectSCDescription = new HashSet<ProjectSCDescription>();
            this.ProjectSCMilestone = new HashSet<ProjectSCMilestone>();
            this.Scope = new HashSet<Scope>();
            this.UserProfile = new HashSet<UserProfile>();
        }
    
        public int ProjectScoreCardID { get; set; }
        public int ProjectID { get; set; }
        public int ScoreCardID { get; set; }
        public bool IsInUse { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> DefaultUMID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public string FPRFilter { get; set; }
        public Nullable<System.DateTime> AcornUpdateDate { get; set; }
        public Nullable<System.DateTime> SMUpdateDate { get; set; }
        public Nullable<System.DateTime> ShortageUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOL> BOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DurationType> DurationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G> G { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportLog> ImportLog { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCActivity> ProjectSCActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCBLS> ProjectSCBLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCDescription> ProjectSCDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCMilestone> ProjectSCMilestone { get; set; }
        public virtual ScoreCard ScoreCard { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scope> Scope { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}
