//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSCActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectSCActivity()
        {
            this.ActivityCCMapping = new HashSet<ActivityCCMapping>();
            this.ImportData = new HashSet<ImportData>();
            this.ProjectSCActivityCC = new HashSet<ProjectSCActivityCC>();
            this.ProjectSCActivityLink = new HashSet<ProjectSCActivityLink>();
            this.ProjectSCSGActivity = new HashSet<ProjectSCSGActivity>();
        }
    
        public int ProjectSCActivityID { get; set; }
        public int ProjectSCID { get; set; }
        public int ActivityID { get; set; }
        public bool IsDefault { get; set; }
        public int DisplaySequence { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityCCMapping> ActivityCCMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportData> ImportData { get; set; }
        public virtual ProjectScoreCard ProjectScoreCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCActivityCC> ProjectSCActivityCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCActivityLink> ProjectSCActivityLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCSGActivity> ProjectSCSGActivity { get; set; }
    }
}
