//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSCActivityCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectSCActivityCC()
        {
            this.ProjectSCActivityCCLog = new HashSet<ProjectSCActivityCCLog>();
        }
    
        public int ProjectSCActivityCCID { get; set; }
        public int ProjectSCActivityID { get; set; }
        public int ProjectCCID { get; set; }
        public int ROC { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsInstalledQty { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ProjectCC ProjectCC { get; set; }
        public virtual ProjectSCActivity ProjectSCActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCActivityCCLog> ProjectSCActivityCCLog { get; set; }
    }
}
