//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSCHistory
    {
        public int ProjectSCHistoryID { get; set; }
        public int ProjectScoreCardID { get; set; }
        public string CostCodeNumber { get; set; }
        public string ScheduleID { get; set; }
        public Nullable<double> AllocatedHrs { get; set; }
        public Nullable<double> EarnedHours { get; set; }
        public Nullable<double> AllocatedQty { get; set; }
        public Nullable<double> EarnedQty { get; set; }
        public System.DateTime CloseDate { get; set; }
        public string FileName { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
