//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectCC()
        {
            this.ActivityCCMapping = new HashSet<ActivityCCMapping>();
            this.GCCBudget = new HashSet<GCCBudget>();
            this.ImportData = new HashSet<ImportData>();
            this.ProjectSCActivityCC = new HashSet<ProjectSCActivityCC>();
            this.ScopeCCBudget = new HashSet<ScopeCCBudget>();
        }
    
        public int ProjectCCID { get; set; }
        public int CostCodeID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> UnitOfMeasureID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ProrateTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityCCMapping> ActivityCCMapping { get; set; }
        public virtual CostCode CostCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCCBudget> GCCBudget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportData> ImportData { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProrateType ProrateType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSCActivityCC> ProjectSCActivityCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScopeCCBudget> ScopeCCBudget { get; set; }
    }
}
