//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSCActivityLink
    {
        public int ProjectSCActivityLinkID { get; set; }
        public int SourceProjectSCActivityID { get; set; }
        public int TargetProjectSCActivityID { get; set; }
    
        public virtual ProjectSCActivity ProjectSCActivity { get; set; }
    }
}
