//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDescriptionTemplate
    {
        public int SCDescriptionTemplateID { get; set; }
        public int ScoreCardID { get; set; }
        public int DescriptionID { get; set; }
        public int DisplaySequence { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual ScoreCard ScoreCard { get; set; }
    }
}
