//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScoreCard()
        {
            this.ProjectScoreCard = new HashSet<ProjectScoreCard>();
            this.SCActivityTemplate = new HashSet<SCActivityTemplate>();
            this.SCDescriptionTemplate = new HashSet<SCDescriptionTemplate>();
            this.SCMilestoneTemplate = new HashSet<SCMilestoneTemplate>();
        }
    
        public int ScoreCardID { get; set; }
        public string ScoreCardName { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> ScoreCardTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectScoreCard> ProjectScoreCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCActivityTemplate> SCActivityTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDescriptionTemplate> SCDescriptionTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCMilestoneTemplate> SCMilestoneTemplate { get; set; }
        public virtual ScoreCardType ScoreCardType { get; set; }
    }
}
