//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCROCTemplate
    {
        public int SCROCTemplateID { get; set; }
        public int SCActivityTemplateID { get; set; }
        public int SCCCTemplateID { get; set; }
        public int ROC { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
