//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileDetail
    {
        public int UserProfileDetailID { get; set; }
        public int UserProfileID { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public Nullable<int> ProjectSCDescriptionID { get; set; }
        public string Color { get; set; }
    
        public virtual ProjectSCDescription ProjectSCDescription { get; set; }
        public virtual Scope Scope { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
