//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XFSEntities : DbContext
    {
        public XFSEntities()
            : base("name=XFSEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityCCGroup> ActivityCCGroup { get; set; }
        public virtual DbSet<ActivityCCMapping> ActivityCCMapping { get; set; }
        public virtual DbSet<ActivityLog> ActivityLog { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<BLSTemplate> BLSTemplate { get; set; }
        public virtual DbSet<BOL> BOL { get; set; }
        public virtual DbSet<BOLDetails> BOLDetails { get; set; }
        public virtual DbSet<BOLReason> BOLReason { get; set; }
        public virtual DbSet<CostCode> CostCode { get; set; }
        public virtual DbSet<CostCodeLog> CostCodeLog { get; set; }
        public virtual DbSet<DDAcorn> DDAcorn { get; set; }
        public virtual DbSet<DDActivityProgress> DDActivityProgress { get; set; }
        public virtual DbSet<DDDes> DDDes { get; set; }
        public virtual DbSet<DDIdList> DDIdList { get; set; }
        public virtual DbSet<Description> Description { get; set; }
        public virtual DbSet<DescriptionLog> DescriptionLog { get; set; }
        public virtual DbSet<DescriptionType> DescriptionType { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentAssignment> DocumentAssignment { get; set; }
        public virtual DbSet<Duration> Duration { get; set; }
        public virtual DbSet<DurationType> DurationType { get; set; }
        public virtual DbSet<EstimateMethod> EstimateMethod { get; set; }
        public virtual DbSet<FPRSource> FPRSource { get; set; }
        public virtual DbSet<G> G { get; set; }
        public virtual DbSet<GCCBudget> GCCBudget { get; set; }
        public virtual DbSet<Holiday> Holiday { get; set; }
        public virtual DbSet<ImportData> ImportData { get; set; }
        public virtual DbSet<ImportDataDescriptionDetail> ImportDataDescriptionDetail { get; set; }
        public virtual DbSet<ImportLog> ImportLog { get; set; }
        public virtual DbSet<ImportRollUp> ImportRollUp { get; set; }
        public virtual DbSet<ImportType> ImportType { get; set; }
        public virtual DbSet<MatGCode> MatGCode { get; set; }
        public virtual DbSet<MatGroupCode> MatGroupCode { get; set; }
        public virtual DbSet<Milestone> Milestone { get; set; }
        public virtual DbSet<ProgressLog> ProgressLog { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectCC> ProjectCC { get; set; }
        public virtual DbSet<ProjectSCActivity> ProjectSCActivity { get; set; }
        public virtual DbSet<ProjectSCActivityCC> ProjectSCActivityCC { get; set; }
        public virtual DbSet<ProjectSCActivityCCLog> ProjectSCActivityCCLog { get; set; }
        public virtual DbSet<ProjectSCActivityLink> ProjectSCActivityLink { get; set; }
        public virtual DbSet<ProjectSCBLS> ProjectSCBLS { get; set; }
        public virtual DbSet<ProjectSCDescription> ProjectSCDescription { get; set; }
        public virtual DbSet<ProjectSCHistory> ProjectSCHistory { get; set; }
        public virtual DbSet<ProjectSCMilestone> ProjectSCMilestone { get; set; }
        public virtual DbSet<ProjectScoreCard> ProjectScoreCard { get; set; }
        public virtual DbSet<ProjectSCSGActivity> ProjectSCSGActivity { get; set; }
        public virtual DbSet<ProjectType> ProjectType { get; set; }
        public virtual DbSet<ProrateType> ProrateType { get; set; }
        public virtual DbSet<QCArea> QCArea { get; set; }
        public virtual DbSet<QCSystem> QCSystem { get; set; }
        public virtual DbSet<QCTag> QCTag { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReportSub> ReportSub { get; set; }
        public virtual DbSet<SCActivityTemplate> SCActivityTemplate { get; set; }
        public virtual DbSet<SCCCTemplate> SCCCTemplate { get; set; }
        public virtual DbSet<SCDescriptionTemplate> SCDescriptionTemplate { get; set; }
        public virtual DbSet<SCMilestoneTemplate> SCMilestoneTemplate { get; set; }
        public virtual DbSet<Scope> Scope { get; set; }
        public virtual DbSet<ScopeCCBudget> ScopeCCBudget { get; set; }
        public virtual DbSet<ScoreCard> ScoreCard { get; set; }
        public virtual DbSet<ScoreCardType> ScoreCardType { get; set; }
        public virtual DbSet<SCROCTemplate> SCROCTemplate { get; set; }
        public virtual DbSet<SGDescription> SGDescription { get; set; }
        public virtual DbSet<SGScheduleMapping> SGScheduleMapping { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasure { get; set; }
        public virtual DbSet<UserName> UserName { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<UserProfileDetail> UserProfileDetail { get; set; }
        public virtual DbSet<UserProfileScorecardViewSettings> UserProfileScorecardViewSettings { get; set; }
        public virtual DbSet<DD> DD { get; set; }
        public virtual DbSet<DDAcornPipeSize> DDAcornPipeSize { get; set; }
        public virtual DbSet<DDActivityPreviousActivity> DDActivityPreviousActivity { get; set; }
        public virtual DbSet<DDBackLogReportView> DDBackLogReportView { get; set; }
        public virtual DbSet<DDChangeCostCodeID> DDChangeCostCodeID { get; set; }
        public virtual DbSet<DDChangeScheduleID> DDChangeScheduleID { get; set; }
        public virtual DbSet<DDRevByISO> DDRevByISO { get; set; }
        public virtual DbSet<DDRevByISOControlNo> DDRevByISOControlNo { get; set; }
        public virtual DbSet<DDRevBySGID> DDRevBySGID { get; set; }
        public virtual DbSet<DDScheduleIDByActivity> DDScheduleIDByActivity { get; set; }
        public virtual DbSet<DDSetZero> DDSetZero { get; set; }
        public virtual DbSet<DDSGActivityProgress> DDSGActivityProgress { get; set; }
        public virtual DbSet<DDSmartPlantMA> DDSmartPlantMA { get; set; }
        public virtual DbSet<DDZeroCostCode> DDZeroCostCode { get; set; }
        public virtual DbSet<Duration_CompactDefaults> Duration_CompactDefaults { get; set; }
        public virtual DbSet<DurationType_Default> DurationType_Default { get; set; }
        public virtual DbSet<DurationVert> DurationVert { get; set; }
    }
}
